// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.Data.GameDatas.Xml
{
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    
    
    public class Expression : XmlData<Expression>
    {
        
        public static String fileName = "Expression";
        
        private System.Collections.Generic.List<string> _expression;
        
        private System.Collections.Generic.List<float> _duration;
        
        public System.Collections.Generic.List<string> expression
        {
            get
            {
                return this._expression;
            }
            set
            {
                this._expression = value;
            }
        }
        
        public System.Collections.Generic.List<float> duration
        {
            get
            {
                return this._duration;
            }
            set
            {
                this._duration = value;
            }
        }
    }
}
