//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetCore.Data.GameDatas
{
    using System;
    using System.Collections.Generic;
    
    
    public class ItemData : GameData<ItemData>
    {
        
        public static String fileName = "ItemData";
        
        private Int32 _itemId;
        
        private Int32 _itemName;
        
        private String _nRemarks;
        
        private Int32 _description;
        
        private String _dRemarks;
        
        private Int32 _icon;
        
        private Int32 _itemType;
        
        private Int32 _itembranch;
        
        private Int32 _gold;
        
        private Int32 _money;
        
        // 
        public Int32 itemId
        {
            get
            {
                return this._itemId;
            }
            set
            {
                this._itemId = value;
            }
        }
        
        // 
        public Int32 itemName
        {
            get
            {
                return this._itemName;
            }
            set
            {
                this._itemName = value;
            }
        }
        
        // 
        public String nRemarks
        {
            get
            {
                return this._nRemarks;
            }
            set
            {
                this._nRemarks = value;
            }
        }
        
        // 
        public Int32 description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }
        
        // 
        public String dRemarks
        {
            get
            {
                return this._dRemarks;
            }
            set
            {
                this._dRemarks = value;
            }
        }
        
        // 
        public Int32 icon
        {
            get
            {
                return this._icon;
            }
            set
            {
                this._icon = value;
            }
        }
        
        // 
        public Int32 itemType
        {
            get
            {
                return this._itemType;
            }
            set
            {
                this._itemType = value;
            }
        }
        
        // 
        public Int32 itembranch
        {
            get
            {
                return this._itembranch;
            }
            set
            {
                this._itembranch = value;
            }
        }
        
        // 
        public Int32 gold
        {
            get
            {
                return this._gold;
            }
            set
            {
                this._gold = value;
            }
        }
        
        // 
        public Int32 money
        {
            get
            {
                return this._money;
            }
            set
            {
                this._money = value;
            }
        }
    }
}
