//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetCore.Data.GameDatas
{
    using System;
    using System.Collections.Generic;
    
    
    public class test : GameData<test>
    {
        
        public static String fileName = "test";
        
        private Int32 _id;
        
        private Single _TestValue;
        
        // 
        public Int32 id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        // 
        public Single TestValue
        {
            get
            {
                return this._TestValue;
            }
            set
            {
                this._TestValue = value;
            }
        }
    }
}
