// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.Data.GameDatas
{
    using System;
    using System.Collections.Generic;
    
    
    public class test : GameData<test>
    {
        
        public static String fileName = "test";
        
        private Int32 _id;
        
        private Single _TestValue;
        
        // 
        public Int32 id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        // 
        public Single TestValue
        {
            get
            {
                return this._TestValue;
            }
            set
            {
                this._TestValue = value;
            }
        }
    }
}
