// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.Data.GameDatas.Protobuf
{
    using System;
    using ProtoBuf;
    
    
    [ProtoBuf.ProtoContract()]
    public class hhoho : ProtobufData<hhoho>
    {
        
        public static string fileName = "hhoho";
        
        private string _test;
        
        private int _asd;
        
        private int _sad;
        
        private int _zxc;
        
        /// 向量哦
        [ProtoBuf.ProtoMember(1)]
        public virtual string test
        {
            get
            {
                return this._test;
            }
            set
            {
                this._test = value;
            }
        }
        
        /// 测试
        [ProtoBuf.ProtoMember(2)]
        public virtual int asd
        {
            get
            {
                return this._asd;
            }
            set
            {
                this._asd = value;
            }
        }
        
        /// 在测试
        [ProtoBuf.ProtoMember(3)]
        public virtual int sad
        {
            get
            {
                return this._sad;
            }
            set
            {
                this._sad = value;
            }
        }
        
        /// 最后测试
        [ProtoBuf.ProtoMember(4)]
        public virtual int zxc
        {
            get
            {
                return this._zxc;
            }
            set
            {
                this._zxc = value;
            }
        }
    }
}
